disabled = false
locale = "en"
label = "English"
weight = 1
title = "Opes Labs"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/tuxavatar.png"
  description = "Mario Dominguez's personal blog."

[params.author]
  name = "Mario Dominguez"
  email = "opeshm@gmail.com"
  image = "img/tuxavatar.png"
  headline = "Notes, experiments, and ideas about software, systems, and product."
  bio = "Mario Dominguez's personal blog."
